import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const dict = {
  en: {
    English: 'English',
    Amharic: 'Amharic',
    'Afaan Oromo': 'Afaan Oromo',
    Search: 'Search',
    'No results found.': 'No results found.',
    Notifications: 'Notifications',
    Settings: 'Settings',
    Logout: 'Logout',
    Bookmarks: 'Bookmarks',
    Courses: 'Courses',
    'Innovation Hub': 'Innovation Hub',
    Research: 'Research',
    Competitions: 'Competitions',
    Events: 'Events',
    Community: 'Community',
    'Sign In': 'Sign In',
    'Get Started': 'Get Started',
    Learn: 'Learn',
    Innovate: 'Innovate',
    Connect: 'Connect',
    'Published courses': 'Published courses',
    'Learning categories': 'Learning categories',
    'Free courses': 'Free courses',
    'Course instructors': 'Course instructors',
    'Browse Courses': 'Browse Courses',
    'Get Started Free': 'Get Started Free',
    'OSTA Learning & Innovation Platform': 'OSTA Learning & Innovation Platform',
    'Empowering Oromia through innovation and technology': 'Empowering Oromia through innovation and technology',
    'Explore': 'Explore',
    'View all courses': 'View all courses',
    'One platform': 'One platform',
    'Learn, innovate, research, and connect': 'Learn, innovate, research, and connect',
    'OSTA brings the core parts of a technology and innovation ecosystem together in one place.': 'OSTA brings the core parts of a technology and innovation ecosystem together in one place.',
    'Start learning': 'Start learning',
    'Featured Courses': 'Featured Courses',
    'Discover courses currently available on the platform.': 'Discover courses currently available on the platform.',
    'Courses are coming soon': 'Courses are coming soon',
    'There are no published courses available yet. Once instructors publish courses, they will appear here automatically.': 'There are no published courses available yet. Once instructors publish courses, they will appear here automatically.',
    'Open Course Marketplace': 'Open Course Marketplace',
    'Stay connected with OSTA events': 'Stay connected with OSTA events',
    'Find workshops, conferences, training sessions, and other events as they are published.': 'Find workshops, conferences, training sessions, and other events as they are published.',
    'View Events': 'View Events',
    'Ready to start learning?': 'Ready to start learning?',
    'Join OSTA and access technology learning, research, innovation, competitions, and community opportunities.': 'Join OSTA and access technology learning, research, innovation, competitions, and community opportunities.',
    "Some platform data couldn't be loaded": "Some platform data couldn't be loaded",
    'Try Again': 'Try Again',
    'Refreshing...': 'Refreshing...',
    'Browse by category': 'Browse by category',
    'Explore real course categories available on OSTA.': 'Explore real course categories available on OSTA.',
    'No course categories are available yet.': 'No course categories are available yet.',
    'Refresh': 'Refresh',
    Welcome: 'Welcome',
    'Welcome back': 'Welcome back',
    'Continue your learning journey with OSTA': 'Continue your learning journey with OSTA',
    'Access your courses, certificates, and research projects across Oromia\'s technology and innovation platform.': 'Access your courses, certificates, and research projects across Oromia\'s technology and innovation platform.',
    'Create a free account to access courses, research, competitions, and a community of learners and innovators.': 'Create a free account to access courses, research, competitions, and a community of learners and innovators.',
    'Join OSTA': 'Join OSTA',
    'Welcome Back': 'Welcome Back',
    'Email': 'Email',
    Password: 'Password',
    'Forgot password?': 'Forgot password?',
    'Enter your password': 'Enter your password',
    'Show password': 'Show password',
    'Hide password': 'Hide password',
    'Or continue with': 'Or continue with',
    "Don't have an account?": "Don't have an account?",
    'Already have an account?': 'Already have an account?',
    'Create Your Account': 'Create Your Account',
    'Create Account': 'Create Account',
    'First Name': 'First Name',
    'Last Name': 'Last Name',
    'Phone': 'Phone',
    'Region': 'Region',
    'Select your region': 'Select your region',
    'Confirm Password': 'Confirm Password',
    'Terms of Service and Privacy Policy': 'Terms of Service and Privacy Policy',
    'I agree to the terms': 'I agree to the terms',
    'Subscribe to updates': 'Subscribe to updates',
    'Register here': 'Register here',
    'Sign in': 'Sign in',
    'Account type': 'Account type',
    'Or register with': 'Or register with',
    'Terms of Service': 'Terms of Service',
    'Privacy Policy': 'Privacy Policy',
    'Subscribe me to OSTA learning news and opportunities': 'Subscribe me to OSTA learning news and opportunities',
    '(optional)': '(optional)',
    'Create account': 'Create account',
    Student: 'Student',
    Instructor: 'Instructor',
    Researcher: 'Researcher',
    Entrepreneur: 'Entrepreneur',
    'Addis Ababa': 'Addis Ababa',
    Adama: 'Adama',
    Bishoftu: 'Bishoftu',
    Jimma: 'Jimma',
    Nekemte: 'Nekemte',
    Shashamane: 'Shashamane',
    Other: 'Other',
    'Enter your first name.': 'Enter your first name.',
    'Enter your last name.': 'Enter your last name.',
    'Select your region.': 'Select your region.',
    'You must agree to the Terms of Service and Privacy Policy.': 'You must agree to the Terms of Service and Privacy Policy.',
    'Google sign-in is not available yet.': 'Google sign-in is not available yet.',
    'GitHub sign-in is not available yet.': 'GitHub sign-in is not available yet.',
    'Login failed. Please try again.': 'Login failed. Please try again.',
    'Registration failed. Please try again.': 'Registration failed. Please try again.',
    'Enter your password.': 'Enter your password.'
  },
  am: {
    English: 'እንግሊዝኛ',
    Amharic: 'አማርኛ',
    'Afaan Oromo': 'ኦሮምኛ',
    Search: 'ፈልግ',
    'No results found.': 'ምንም ውጤት አልተገኘም።',
    Notifications: 'ማሳወቂያዎች',
    Settings: 'ቅንብሮች',
    Logout: 'ውጣ',
    Bookmarks: 'የተቀመጡ',
    Courses: 'ኮርሶች',
    'Innovation Hub': 'ኢኖቬሽን ሃብት',
    Research: 'ምርምር',
    Competitions: 'ውድድሮች',
    Events: 'ክስተቶች',
    Community: 'ማህበረሰብ',
    'Sign In': 'ግባ',
    'Get Started': 'ጀምር',
    Learn: 'ተማር',
    Innovate: 'ፈጥር',
    Connect: 'ተገናኘ',
    'Published courses': 'የታተመ ኮርሶች',
    'Learning categories': 'የመማር ምድቦች',
    'Free courses': 'ነፃ ኮርሶች',
    'Course instructors': 'የኮርስ አስተማሪዎች',
    'Browse Courses': 'ኮርሶችን መቃኘት',
    'Get Started Free': 'ነፃ ጀምር',
    'OSTA Learning & Innovation Platform': 'የኦስታ ትምህርት እና ኢኖቬሽን መድረክ',
    'Empowering Oromia through innovation and technology': 'ኦሮሚያን በፈጠራ እና ቴክኖሎጂ በማጉላት',
    'Explore': 'ያስሱ',
    'View all courses': 'ሁሉንም ኮርሶች ተመልከት',
    'One platform': 'አንድ መድረክ',
    'Learn, innovate, research, and connect': 'ተማር፣ ፈጥር፣ ምርምር እና ተገናኘ',
    'OSTA brings the core parts of a technology and innovation ecosystem together in one place.': 'ኦስታ የቴክኖሎጂ እና ፈጠራ ስርዓትን ቁልፍ ክፍሎች በአንድ ቦታ ያስተሳስራል።',
    'Start learning': 'መጀመር',
    'Featured Courses': 'ተለይተው የሚታዩ ኮርሶች',
    'Discover courses currently available on the platform.': 'በመድረክ ላይ አሁን የሚገኙትን ኮርሶች ያግኙ።',
    'Courses are coming soon': 'ኮርሶች በቅርቡ ይመጣሉ',
    'There are no published courses available yet. Once instructors publish courses, they will appear here automatically.': 'አሁን ምንም የታተመ ኮርስ የለም። አስተማሪዎች ኮርሶችን ካሳተሙ እዚህ በራስ-ሰር ይታያሉ።',
    'Open Course Marketplace': 'የኮርስ ገበያ ክፈት',
    'Stay connected with OSTA events': 'ከኦስታ ክስተቶች ጋር ይገናኙ',
    'Find workshops, conferences, training sessions, and other events as they are published.': 'ክፍለ ጊዜዎች፣ ኮንፌረንሶች፣ አሰልጣኝ ክፍለ ጊዜዎችን እና ሌሎች ክስተቶችን በታተመበት ጊዜ ያግኙ።',
    'View Events': 'ክስተቶችን ይመልከቱ',
    'Ready to start learning?': 'መጀመር ዝግጁ ነዎት?',
    'Join OSTA and access technology learning, research, innovation, competitions, and community opportunities.': 'ኦስታን ተቀላቀል እና የቴክኖሎጂ ትምህርት፣ ምርምር፣ ፈጠራ፣ ውድድሮች እና የማህበረሰብ እድሎችን ያግኙ።',
    "Some platform data couldn't be loaded": 'አንዳንድ የመድረክ መረጃ ሊጫኑ አልቻሉም',
    'Try Again': 'ዳግም ይሞክሩ',
    'Refreshing...': 'በማደስ ላይ...',
    'Browse by category': 'በምድብ ያስሱ',
    'Explore real course categories available on OSTA.': 'በኦስታ ላይ የሚገኙትን እውነተኛ የኮርስ ምድቦች ያስሱ።',
    'No course categories are available yet.': 'አሁን ምንም የኮርስ ምድቦች የሉም።',
    'Refresh': 'አድስ',
    Welcome: 'እንኳን በደህና መጡ',
    'Welcome back': 'እንኳን ተመለሱ',
    'Continue your learning journey with OSTA': 'ከኦስታ ጋር የመማር ጉዞዎን ይቀጥሉ',
    'Access your courses, certificates, and research projects across Oromia\'s technology and innovation platform.': 'ኮርሶችዎን፣ የምስክር ወረቀቶችዎን እና የምርምር ፕሮጀክቶችዎን በኦሮሚያ ቴክኖሎጂ እና ፈጠራ መድረክ ላይ ያግኙ።',
    'Create a free account to access courses, research, competitions, and a community of learners and innovators.': 'ኮርሶችን፣ ምርምርን፣ ውድድሮችን እና የተማሪዎችን እና ፈጣሪዎችን ማህበረሰብን ለመድረስ ነፃ መለያ ይፍጠሩ።',
    'Join OSTA': 'ኦስታን ተቀላቀል',
    'Welcome Back': 'እንኳን ተመለሱ',
    Email: 'ኢሜይል',
    Password: 'የይለፍ ቃል',
    'Forgot password?': 'የይለፍ ቃል ረሱ?',
    'Enter your password': 'የይለፍ ቃልዎን ያስገቡ',
    'Show password': 'የይለፍ ቃል አሳይ',
    'Hide password': 'የይለፍ ቃል ደብቅ',
    'Or continue with': 'ወይም ተጨማሪ ያስተካክሉ',
    "Don't have an account?": 'መለያ የለዎትም?',
    'Already have an account?': 'አስቀድሞ መለያ አለዎት?',
    'Create Your Account': 'መለያዎን ይፍጠሩ',
    'Create Account': 'መለያ ይፍጠሩ',
    'First Name': 'ስም',
    'Last Name': 'አያት ስም',
    'Phone': 'ስልክ',
    'Region': 'ክልል',
    'Select your region': 'ክልልዎን ይምረጡ',
    'Confirm Password': 'የይለፍ ቃል አረጋግጥ',
    'Terms of Service and Privacy Policy': 'የአገልግሎት መመሪያ እና የግላዊነት ፖሊሲ',
    'I agree to the terms': 'እኔ ሁኔታዎችን ተስማምቻለሁ',
    'Subscribe to updates': 'ለዝመናዎች ይመዝገቡ',
    'Register here': 'እዚህ ይመዝገቡ',
    'Sign in': 'ግባ',
    'Account type': 'የመለያ አይነት',
    'Or register with': 'በዚህ ይመዝገቡ',
    'Terms of Service': 'የአገልግሎት መመሪያ',
    'Privacy Policy': 'የግላዊነት ፖሊሲ',
    'Subscribe me to OSTA learning news and opportunities': 'ለኦስታ የመማር ዜና እና እድሎች ይመዝገቡ',
    '(optional)': '(አማራጭ)',
    'Create account': 'መለያ ፍጠር',
    Student: 'ተማሪ',
    Instructor: 'አስተማሪ',
    Researcher: 'ምርምር',
    Entrepreneur: 'ኢንተርፕሪዘር',
    'Addis Ababa': 'አዲስ አበባ',
    Adama: 'አዳማ',
    Bishoftu: 'ቢሾፍቱ',
    Jimma: 'ጅማ',
    Nekemte: 'ነቀምቴ',
    Shashamane: 'ሻሸመኔ',
    Other: 'ሌላ',
    'Enter your first name.': 'ስምዎን ያስገቡ።',
    'Enter your last name.': 'የአያት ስምዎን ያስገቡ።',
    'Select your region.': 'ክልልዎን ይምረጡ።',
    'You must agree to the Terms of Service and Privacy Policy.': 'ለአገልግሎት መመሪያ እና የግላዊነት ፖሊሲ መስማማት አለብዎት።',
    'Google sign-in is not available yet.': 'Google መግቢያ አሁን አይገኝም።',
    'GitHub sign-in is not available yet.': 'GitHub መግቢያ አሁን አይገኝም።',
    'Login failed. Please try again.': 'መግባት አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'Registration failed. Please try again.': 'ምዝገባ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'Enter your password.': 'የይለፍ ቃልዎን ያስገቡ።'
  },
  om: {
    English: 'Ingiliffa',
    Amharic: 'Amaariiffaa',
    'Afaan Oromo': 'Afaan Oromoo',
    Search: 'Barbaadi',
    'No results found.': 'Bu’aan hin argamne.',
    Notifications: 'Beeksisa',
    Settings: 'Qindaa’ina',
    Logout: 'Ba’i',
    Bookmarks: 'Kan kuufame',
    Courses: 'Kursiiwwan',
    'Innovation Hub': 'Innovation Hub',
    Research: 'Qorannoo',
    Competitions: 'Dorgommi',
    Events: 'Biyyoonni',
    Community: 'Hawaasummaa',
    'Sign In': 'Seeni',
    'Get Started': 'Jalqabu',
    Learn: 'Baradhu',
    Innovate: 'Qopheeffadhu',
    Connect: 'Walqunnamtii',
    'Published courses': 'Kursiwwan maxxanfaman',
    'Learning categories': 'Gosa barnootaa',
    'Free courses': 'Kursiwwan bilisaa',
    'Course instructors': 'Barsiisota kursii',
    'Browse Courses': 'Kursiiwwan barbaadi',
    'Get Started Free': 'Bilisa jalqabu',
    'OSTA Learning & Innovation Platform': 'Mala Barnootaa fi Qopheefannaa OSTA',
    'Empowering Oromia through innovation and technology': 'Oromiyaa oomishaalee teeknooloojii fi furmaata haaraa waliin dandeessisu',
    'Explore': 'Qoradhu',
    'View all courses': 'Kursiiwwan hunda ilaali',
    'One platform': 'Mala tokko',
    'Learn, innovate, research, and connect': 'Baradhu, qopheeffadhu, qoradhu, fi walqunnamtii',
    'OSTA brings the core parts of a technology and innovation ecosystem together in one place.': 'OSTA qooda core of ecosystem teeknooloojii fi qopheefannaa tokkotti walitti qabata.',
    'Start learning': 'Barnoota jalqabu',
    'Featured Courses': 'Kursiiwwan adda darban',
    'Discover courses currently available on the platform.': 'Kursiiwwan amma meeshaawwan irratti argaman barbaadi.',
    'Courses are coming soon': 'Kursiwwan dhihooftu',
    'There are no published courses available yet. Once instructors publish courses, they will appear here automatically.': 'Kursiwwan maxxanfaman amma hin jiru. Barsiisonni yoon maxxanuu, asitti ofumaan mulatu.',
    'Open Course Marketplace': 'Gatii Kursii Bani',
    'Stay connected with OSTA events': 'Walqina OSTA taatee waliin hordof',
    'Find workshops, conferences, training sessions, and other events as they are published.': 'Worikshopii, konferensii, barnoota, fi taatee biroo kan maxxanfamu argadhu.',
    'View Events': 'Taatee ilaali',
    'Ready to start learning?': 'Barnoota jalqabuu qophaa?',
    'Join OSTA and access technology learning, research, innovation, competitions, and community opportunities.': 'OSTA waliin hirmaadhu fi barnoota teeknoolojii, qorannoo, qopheeffannaa, dorgommi, fi hawaasummaa argadhu.',
    "Some platform data couldn't be loaded": 'Qindoomina malaa tokko tokko hin feene',
    'Try Again': 'Irra deebi\'i yaali',
    'Refreshing...': 'Haaraa jiraachuu...',
    'Browse by category': 'Gosaadhaan barbaadi',
    'Explore real course categories available on OSTA.': 'Gosa barnootaa dhugaa OSTA irratti argaman barbaadi.',
    'No course categories are available yet.': 'Gosa barnootaa amma hin jiru.',
    'Refresh': 'Haaraa',
    Welcome: 'Baga naggale',
    'Welcome back': 'Baga naggale deebi\'a',
    'Continue your learning journey with OSTA': 'OSTA waliin safartuu barnoota kee itti fuf',
    'Access your courses, certificates, and research projects across Oromia\'s technology and innovation platform.': 'Kursiiwwan, sertifikaattota, fi piroojektoota qorannoo kee akka OSTA irraa argadhu.',
    'Create a free account to access courses, research, competitions, and a community of learners and innovators.': 'Kursiiwwan, qorannoo, dorgommi, fi hawaasummaa barattootaa fi qopheefattootaa argachuuf seenaa bilisaa uumi.',
    'Join OSTA': 'OSTA waliin hirmaadhu',
    'Welcome Back': 'Baga naggale deebi\'a',
    Email: 'Imeelii',
    Password: 'Jecha iccitii',
    'Forgot password?': 'Jecha iccitii dagattee?',
    'Enter your password': 'Jecha iccitii keessan galchaa',
    'Show password': 'Jecha iccitii agarsiisi',
    'Hide password': 'Jecha iccitii dhoksi',
    'Or continue with': 'Ykn itti fuf',
    'Already have an account?': 'Miila seenaa duraan qabdaa?',
    'Create Your Account': 'Miila seenaa uumi',
    'First Name': 'Maqaa',
    'Last Name': 'Maqaa akaakuu',
    'Phone': 'Bilbila',
    'Region': 'Naannoo',
    'Select your region': 'Naannoo keessan filadhaa',
    'Terms of Service and Privacy Policy': 'Waliigaltee tajaajila fi siyaasinaa dhunfaa',
    'I agree to the terms': 'Waliigala',
    'Subscribe to updates': 'Haaromsaaf galmaa\'i',
    'Register here': 'Asitti galmaa\'i',
    'Sign in': 'Seeni',
    'Account type': 'Gosa seenaa',
    Student: 'Barataa',
    Instructor: 'Barsiisaa',
    Researcher: 'Qorataa',
    Entrepreneur: 'Daldaaltuu',
    'Addis Ababa': 'Finfinne',
    Adama: 'Adaamaa',
    Bishoftu: 'Bishooftu',
    Jimma: 'Jimmaa',
    Nekemte: 'Nekemte',
    Shashamane: 'Shaashamane',
    Other: 'Kan biraa',
    'Enter your first name.': 'Maqaa keessan galchaa.',
    'Enter your last name.': 'Maqaa akaakuu keessan galchaa.',
    'Select your region.': 'Naannoo keessan filadhaa.',
    'You must agree to the Terms of Service and Privacy Policy.': 'Waliigaltee tajaajila fi siyaasinaa dhunfaa fudhachuu qabdu.',
    'Google sign-in is not available yet.': 'Google seensa amma hin jiru.',
    'GitHub sign-in is not available yet.': 'GitHub seensa amma hin jiru.',
    'Login failed. Please try again.': 'Seensa hin milkoofne. Maaloo irra deebi\'i yaali.',
    'Registration failed. Please try again.': 'Galmaa\'iinsaa hin milkoofne. Maaloo irra deebi\'i yaali.',
    'Enter your password.': 'Jecha iccitii keessan galchaa.'
  }
};

export const getTranslation = (key, locale = 'en') => dict[locale]?.[key] ?? dict.en[key] ?? key;

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('osta_language');
    return saved || 'en';
  });

  const changeLanguage = (value) => {
    setLanguage(value);
    localStorage.setItem('osta_language', value);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: changeLanguage,
      t: (key) => getTranslation(key, language),
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
