const authService=require('../services/authService');
const authController={
 async register(req,res){try{const {firstName,lastName,email,phone,region,password,accountType}=req.body;if(!firstName||!lastName||!email||!phone||!region||!password||!accountType)return res.status(400).json({message:'All registration fields are required'});const result=await authService.register({firstName,lastName,email,phone,region,password,accountType});res.status(201).json({message:'Registration successful. Check your email to verify your account.',...result});}catch(e){console.error(e);res.status(400).json({message:e.message});}},
 async login(req,res){try{const {email,password}=req.body;if(!email||!password)return res.status(400).json({message:'Email and password are required'});res.json({message:'Login successful',...await authService.login(email,password)});}catch(e){res.status(401).json({message:e.message});}},
 async verifyEmail(req,res){try{res.json(await authService.verifyEmail(req.body.email,req.body.code));}catch(e){res.status(400).json({message:e.message});}},
 async resendVerification(req,res){try{res.json(await authService.resendVerification(req.body.email));}catch(e){res.status(400).json({message:e.message});}},
 async requestReset(req,res){try{const data=await authService.requestReset(req.body.email||'');res.json({message:'If an account exists for that email, a reset code has been sent.'});}catch(e){console.error(e);res.json({message:'If an account exists for that email, a reset code has been sent.'});}},
 async verifyResetCode(req,res){try{const data=await authService.verifyResetCode(req.body.email,req.body.code);res.json({message:'Code verified',resetToken:data.resetToken});}catch(e){res.status(400).json({message:e.message});}},
 async resetPassword(req,res){try{const {resetToken,newPassword}=req.body;if(!resetToken||!newPassword)return res.status(400).json({message:'Reset token and new password are required'});res.json(await authService.resetPassword(resetToken,newPassword));}catch(e){res.status(400).json({message:e.message});}}
};module.exports=authController;
