const pool=require('../config/database');
const Notification=require('../models/Notification');
const eventController={
 async getAll(req,res){try{const [rows]=await pool.execute(`SELECT e.*,CONCAT(u.first_name,' ',u.last_name) creator_name FROM events e LEFT JOIN users u ON e.instructor_id=u.id WHERE e.status IS NULL OR e.status IN ('published','active','upcoming') ORDER BY e.event_date ASC,e.start_time ASC`);res.json(rows);}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to fetch events'});}},
 async getMyEvents(req,res){try{const [rows]=await pool.execute(`SELECT * FROM events WHERE instructor_id=? ORDER BY event_date DESC,start_time DESC`,[req.user.id]);res.json({success:true,data:rows});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to fetch your events'});}},
 async getAdminEvents(req,res){try{const [rows]=await pool.execute(`SELECT e.*,CONCAT(u.first_name,' ',u.last_name) creator_name FROM events e LEFT JOIN users u ON e.instructor_id=u.id ORDER BY e.event_date DESC,e.start_time DESC`);res.json({success:true,data:rows});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to fetch events'});}},
 async getById(req,res){try{const [[event]]=await pool.execute(`SELECT e.*,CONCAT(u.first_name,' ',u.last_name) creator_name FROM events e LEFT JOIN users u ON e.instructor_id=u.id WHERE e.id=?`,[req.params.id]);if(!event)return res.status(404).json({success:false,message:'Event not found'});res.json({success:true,data:event});}catch(e){res.status(500).json({success:false,message:'Failed to fetch event'});}},
 async create(req,res){try{const b=req.body; if(!String(b.title||'').trim()||!b.event_date||!b.start_time||!String(b.location_or_link||'').trim())return res.status(400).json({success:false,message:'Title, date, time and location/link are required'});const [r]=await pool.execute(`INSERT INTO events (instructor_id,title,category,description,event_date,start_time,duration_hours,delivery_mode,location_or_link,capacity,banner_image,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[req.user.id,b.title.trim(),b.category||'General',b.description||null,b.event_date,b.start_time,Number(b.duration_hours)||2,b.delivery_mode||'online',b.location_or_link.trim(),Number(b.capacity)||100,b.banner_image||null,b.status||'draft']);res.status(201).json({success:true,message:'Event created successfully',data:{id:r.insertId}});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to create event'});}},
 async update(req,res){try{const [[event]]=await pool.execute(`SELECT id,instructor_id FROM events WHERE id=?`,[req.params.id]);if(!event)return res.status(404).json({success:false,message:'Event not found'});if(req.user.role!=='admin'&&Number(event.instructor_id)!==Number(req.user.id))return res.status(403).json({success:false,message:'You are not allowed to update this event'});const b=req.body;const [r]=await pool.execute(`UPDATE events SET title=?,category=?,description=?,event_date=?,start_time=?,duration_hours=?,delivery_mode=?,location_or_link=?,capacity=?,banner_image=?,status=? WHERE id=?`,[b.title,b.category||'General',b.description||null,b.event_date,b.start_time,Number(b.duration_hours)||2,b.delivery_mode||'online',b.location_or_link,Number(b.capacity)||100,b.banner_image||null,b.status||'draft',req.params.id]);if(!r.affectedRows)return res.status(404).json({success:false,message:'Event not found'});if(b.status==='published')await notifyUsers(`New OSTA event: ${b.title}`,`A new event has been published: ${b.title}`,'Events');res.json({success:true,message:'Event updated successfully'});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to update event'});}},
 async delete(req,res){try{const [[event]]=await pool.execute(`SELECT id,instructor_id FROM events WHERE id=?`,[req.params.id]);if(!event)return res.status(404).json({success:false,message:'Event not found'});if(req.user.role!=='admin'&&Number(event.instructor_id)!==Number(req.user.id))return res.status(403).json({success:false,message:'You are not allowed to delete this event'});await pool.execute(`DELETE FROM events WHERE id=?`,[req.params.id]);res.json({success:true,message:'Event deleted successfully'});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to delete event'});}},
 async status(req,res){try{const [[event]]=await pool.execute(`SELECT * FROM events WHERE id=?`,[req.params.id]);if(!event)return res.status(404).json({success:false,message:'Event not found'});if(req.user.role!=='admin'&&Number(event.instructor_id)!==Number(req.user.id))return res.status(403).json({success:false,message:'Not authorized'});await pool.execute(`UPDATE events SET status=? WHERE id=?`,[req.body.status,req.params.id]);if(req.body.status==='published')await notifyUsers(`New OSTA event: ${event.title}`,`A new event has been published: ${event.title}`,'Events');res.json({success:true,message:'Event status updated'});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to update event status'});}}
};
async function notifyUsers(title,message,category){try{const [users]=await pool.execute(`SELECT id FROM users WHERE status IS NULL OR status='active'`);for(const u of users)await Notification.create({userId:u.id,title,message,category,entityType:'event',entityId:null,targetPath:'/events'});}catch(e){console.warn('Event notification error:',e.message);}}
module.exports=eventController;
