import {useEffect,useState} from 'react';
import {useNavigate,useParams,useLocation} from 'react-router-dom';
import api from '@services/api';
import Button from '@components/ui/Button';
const EMPTY={title:'',category:'Workshop',description:'',event_date:'',start_time:'',duration_hours:2,delivery_mode:'online',location_or_link:'',capacity:100,status:'draft'};
export default function CreateEvent(){const nav=useNavigate();const route=useLocation();const {id}=useParams();const editing=Boolean(id);const [form,setForm]=useState(EMPTY);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(editing);const [error,setError]=useState('');
useEffect(()=>{if(!editing)return;api.get(`/events/${id}`).then(r=>setForm({...EMPTY,...(r.data?.data||{})})).catch(e=>setError(e.response?.data?.message||'Failed to load event')).finally(()=>setLoading(false))},[editing,id]);
async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(editing)await api.put(`/events/${id}`,form);else await api.post('/events',form);nav(editing&&route.pathname.startsWith('/admin')?'/admin/events':'/instructor/events')}catch(err){setError(err.response?.data?.message||'Failed to save event')}finally{setBusy(false)}}
if(loading)return <div className="py-12 text-center text-slate-500">Loading event...</div>;
return <section><h1 className="text-3xl font-black text-ink dark:text-white">{editing?'Edit Event':'Create Event'}</h1><p className="mt-2 text-sm text-slate-500">Manage professional OSTA workshops, webinars and innovation events.</p><form onSubmit={submit} className="mt-7 space-y-6 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="grid gap-5 md:grid-cols-2">{[['title','Event title'],['category','Category'],['event_date','Event date'],['start_time','Start time'],['duration_hours','Duration (hours)'],['capacity','Capacity'],['location_or_link','Location or meeting link']].map(([key,label])=><label key={key} className="block text-sm font-semibold text-ink dark:text-white">{label}<input required={['title','event_date','start_time','location_or_link'].includes(key)} type={key==='event_date'?'date':key==='start_time'?'time':key==='duration_hours'||key==='capacity'?'number':'text'} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950"/></label>)}</div><label className="block text-sm font-semibold text-ink dark:text-white">Delivery mode<select value={form.delivery_mode} onChange={e=>setForm({...form,delivery_mode:e.target.value})} className="mt-2 h-11 w-full rounded-lg border px-3"><option value="online">Online</option><option value="in_person">In person</option><option value="hybrid">Hybrid</option></select></label><label className="block text-sm font-semibold text-ink dark:text-white">Status<select value={form.status||'draft'} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 h-11 w-full rounded-lg border px-3"><option value="draft">Draft</option><option value="published">Published</option><option value="active">Active</option><option value="completed">Completed</option></select></label><label className="block text-sm font-semibold text-ink dark:text-white">Description<textarea rows="5" value={form.description??''} onChange={e=>setForm({...form,description:e.target.value})} className="mt-2 w-full rounded-lg border p-3 dark:bg-slate-950"/></label>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>nav(-1)}>Cancel</Button><Button disabled={busy}>{busy?'Saving...':editing?'Save changes':'Create event'}</Button></div></form></section>}
